name: Deploy to Cloud Run (GCP)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/redactor-repo/agentic-redactor .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/redactor-repo/agentic-redactor

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy redactor-service \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/redactor-repo/agentic-redactor \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
